public class AccCnt {
//added comments for develop branch
//added comments for master branch
	//comments for feature branch
	//just
	//one more line
	//added second line
integer i;
string name;
public string GetName() {
    return this.name; 
}

	public integer getI() {
		return this.i;
	}

	public void setI(integer i) {
		this.i = i;
	}


	public void setName(string name) {
		this.name = name;
	}

}
